[project]
name = "learn-deepeval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepeval>=3.7.9",
    "grandalf>=0.8",
    "langgraph>=1.0.6",
]
